pipeline{
    agent { docker { image 'imagename:tag' } }
    stages{
        stage('Build'){
            steps{
                sh 'node --version'
            }
        }
    }
}

--------------------------------

pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'node --version'
            }
        }
    }
}